package main

import (
	"bytes"
	"fmt"
	"log"
	"os"
	"strconv"

	"github.com/lestrrat-go/codegen"
	"github.com/pkg/errors"
)

func main() {
	if err := _main(); err != nil {
		log.Printf("%s", err)
		os.Exit(1)
	}
}

func _main() error {
	var buf bytes.Buffer

	buf.WriteString("package dom")
	buf.WriteString("\n\n// Auto-generated by internal/cmd/genwrapnode/genwrapnode.go. DO NOT EDIT!")
	buf.WriteString("\n\nimport (")
	buf.WriteString("\n\"fmt\"\n")
	for _, lib := range []string{"github.com/lestrrat-go/libxml2/clib", "github.com/lestrrat-go/libxml2/types"} {
		fmt.Fprintf(&buf, "\n%s", strconv.Quote(lib))
	}
	buf.WriteString("\n)")

	nodeTypes := []string{
		`Namespace`,
		`Attribute`,
		`CDataSection`,
		`Comment`,
		`Element`,
		`Text`,
		`Pi`,
	}

	for _, typ := range nodeTypes {
		fmt.Fprintf(&buf, "\n\nfunc wrap%sNode(ptr uintptr) *%s {", typ, typ)
		fmt.Fprintf(&buf, "\nvar n %s", typ)
		buf.WriteString("\nn.ptr = ptr")
		buf.WriteString("\nreturn &n")
		buf.WriteString("\n}")
	}

	buf.WriteString("\n\n// WrapNode is a function created with the sole purpose of allowing")
	buf.WriteString("\n// go-libxml2 consumers that can generate a C.xmlNode pointer to")
	buf.WriteString("\n// create libxml2.Node types, e.g. go-xmlsec.")
	buf.WriteString("\nfunc WrapNode(n uintptr) (types.Node, error) {")
	buf.WriteString("\nswitch typ := clib.XMLGetNodeTypeRaw(n); typ {")

	for _, typ := range nodeTypes {
		// XXX hmm, this never existed. don't have time to debug right now.
		// possibly an omission bug?
		if typ == "Namespace" {
			continue
		}
		fmt.Fprintf(&buf, "\ncase clib.%sNode:", typ)
		fmt.Fprintf(&buf, "\nreturn wrap%sNode(n), nil", typ)
	}

	buf.WriteString("\ndefault:")
	buf.WriteString("\nreturn nil, fmt.Errorf(\"unknown node: %d\", typ)")

	buf.WriteString("\n}")
	buf.WriteString("\n}")

	srcbytes := buf.Bytes() // save so we can use in error reporting later
	if err := codegen.WriteFile("dom/node_wrap.go", &buf, codegen.WithFormatCode(true)); err != nil {
		_ = codegen.Write(os.Stdout, bytes.NewReader(srcbytes), codegen.WithLineNumber(true))
		return errors.Wrap(err, `failed to format code`)
	}
	return nil
}
